{% set python_min = "3.11" %}
{% set name = "pyiron_workflow" %}
{% set version = "0.18.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyiron_workflow-{{ version }}.tar.gz
  sha256: 428d0e3501f0556c7a7a5b52e62c147f7018290c3518fd531f44529b480b6de7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling ==1.30.1
    - hatch-vcs ==0.5.0
    - bagofholding
    - bidict
    - cloudpickle
    - executorlib
    - flowrep
    - networkx
    - pandas
    - pint
    - pyiron_snippets
    - python-graphviz
    - rdflib
    - semantikon
    - toposort
    - typeguard
  run:
    - python >={{ python_min }},<3.14
    - bagofholding >=0.1.12,<0.2.0
    - bidict ==0.23.1
    - cloudpickle >=3.0.0,<3.2.0
    - executorlib >=1.5.3,<1.11.0
    - flowrep >=0.6.0,<0.7.0
    - networkx >=3.5.0,<3.7.0
    - pandas >=2.2.2,<3.1.0
    - pint >=0.24,<=0.25.3
    - pyiron_snippets >=1.3.0,<2.0.0
    - python-graphviz >=0.20.3,<=0.21
    - rdflib >=7.1.4,<7.7.0
    - semantikon >=1.4.0,<1.5.0
    - toposort ==1.10
    - typeguard >=4.2.0,<4.6.0

test:
  imports:
    - pyiron_workflow
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/pyiron/pyiron_workflow
  summary: Graph-and-node based workflow tools.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - liamhuber
    - srmnitc
    - pyiron-runner
    - jan-janssen
    - pmrv
    - niklassiemer
